enable_audio: false

inputs:
  - type: test_video
    pattern: 18
    width: 320
    height: 180
  - type: test_video
    pattern: 18
    width: 320
    height: 180
  - type: test_video
    pattern: 18
    width: 320
    height: 180
  - type: test_video
    pattern: 18
    width: 320
    height: 180

outputs:
  - type: local

mixers:
  - width: 640
    height: 360
    sources:
    - uid: input1
      width: 320
      height: 180
    - uid: input2
      xpos: 320
      width: 320
      height: 180
    - uid: input3
      ypos: 180
      width: 320
      height: 180
    - uid: input4
      xpos: 320
      ypos: 180
      width: 320
      height: 180
