enable_video: false

inputs:
    - type: test_audio
      props:
          freq: 200
    - type: test_audio
      props:
          freq: 400
          volume: 1.0
    - type: test_audio
      props:
          freq: 600
          volume: 0.2

outputs:
    - type: local
