api_port: 5001

enable_audio: false

inputs:
  - id: 1 # IMAGE OVERLAY BACKGROUND
    name: image-background
    type: image
    uri: file:///Users/spieglio/Documents/obs-graphics/niyama.academy/tv-chanel/background-video@720p.png
    width: 640
    height: 360
    state: PLAYING

  - id: 500 # NIYAMA PLAYLIST STREAM
    name: rtmpsrc-playlist-ingest
    type: uri
    uri: rtmp://stream.spiegl.co/live/lTgpsAp0x
    buffer_duration: 5000
    loop: True
    width: 320
    height: 180

  - id: 501
    name: rtmpsrc-live-ingest
    type: uri
    uri: rtmp://stream.spiegl.co/live/Fpe6J5Bzl
    buffer_duration: 5000
    loop: True
    width: 320
    height: 180

  - id: 502
    name: dummy
    type: 'test_video'
    pattern: 2
    width: 320
    height: 180

  - id: 900
    name: rtmpsrc-live-public
    type: uri
    uri: rtmp://stream.spiegl.co/live/Fpe6J5Bzl
    # uri: rtmp://stream.spiegl.co/live/sYyMhR4zu
    buffer_duration: 5000
    loop: True
    width: 320
    height: 180

mixers:
  - id: 100
    width: 640
    height: 360
    pattern: black # Background for the Main Mixer
    background: transparent
    sources:
    - uid: input1
      width: 640
      height: 360
    - uid: input500
      width: 320
      height: 180
    - uid: input501
      xpos: 320
      width: 320
      height: 180
    - uid: input502
      ypos: 180
      width: 320
      height: 180
    - uid: input900
      xpos: 320
      ypos: 180
      width: 320
      height: 180


overlays:
  - type: text
    visible: true
    text: 'PLAYLIST INGEST'
    source: input500
    valignment: bottom
    halignment: center
    fontDesc: "Raleway 30"
    shadedBackground: True
  - type: text
    visible: true
    text: 'LIVE INGEST'
    source: input501
    valignment: bottom
    halignment: center
    fontDesc: "Raleway 30"
    shadedBackground: True
  - type: text
    visible: true
    text: 'DUMMY'
    source: input502
    valignment: bottom
    halignment: center
    fontDesc: "Raleway 30"
    shadedBackground: True
  - type: text
    visible: true
    text: 'LIVE OUTPUT'
    source: input900
    valignment: bottom
    halignment: center
    fontDesc: "Raleway 30"
    shadedBackground: True
  - type: clock
    visible: true
    source: mixer100
    valignment: bottom
    halignment: center
    timeFormat: '%Y-%m-%d %H:%M:%S %Z'
    fontDesc: "Raleway Mono 10"
    shadedBackground: True

outputs:
  - type: 'image'
    location: './public/gstreamer/wall.jpg'
    width: 1280
    height: 720
    update_frequency: 1
  # - type: tcp
  #   name: outputTcp
  #   source: mixer100
  #   host: 127.0.0.1
  #   port: 7005
  #   width: 1280
  #   height: 720